version: '3.7'
networks:
  mongo-net:
    name: mongo-net
services:
  mongo-2:
    container_name: mongo-2
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/mongo.key", "--replSet", "navaidBlogs", "--journal", "--bind_ip_all" ]
    ports:
    - "30002:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./mongo.key:/data/mongo.key"

  mongo-1:
    container_name: mongo-1
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/mongo.key", "--replSet", "navaidBlogs", "--journal", "--bind_ip_all" ]
    ports:
    - "30001:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./mongo.key:/data/mongo.key"

  mongo-0:
    container_name: mongo-0
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/mongo.key", "--replSet", "navaidBlogs", "--journal", "--bind_ip_all" ]
    ports:
    - "30000:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./setup.sh:/scripts/setup.sh"
    - "./mongod.conf:/etc/mongod.conf"
    - "./mongo.key:/data/mongo.key"
